### create task
POST localhost:8080/tasks
Content-Type: application/json

{
  "name":"call the police",
  "status": "pending"
}

### get task
GET localhost:8080/tasks/1
Content-Type: application/json

### get tasks
GET localhost:8080/tasks
Content-Type: application/json

### set task status
POST localhost:8080/tasks/1
Content-Type: application/json

{
  "status": "pending"
}

### delete task
DELETE localhost:8080/tasks/1
Content-Type: application/json

###
